name: mobile_ecommerce
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bounceable: ^1.1.0
  flutter_localizations:
    sdk: flutter
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400

    - family: Kh Content
      fonts:
        - asset: assets/fonts/kh_content/Kh-Content.ttf

    - family: Kantumruy Pro
      fonts:
        - asset: assets/fonts/kantumruyPro/KantumruyPro-Regular.ttf
        - asset: assets/fonts/kantumruyPro/KantumruyPro-Bold.ttf
          weight: 700

    - family: Preahvihear
      fonts:
        - asset: assets/fonts/preahvihear/Preahvihear.ttf

    - family: AbrilFatface
      fonts:
        - asset: assets/fonts/others/AbrilFatface-Regular.otf

    - family: Rosela
      fonts:
        - asset: assets/fonts/others/Rosela.ttf

    - family: Dosis
      fonts:
        - asset: assets/fonts/others/Dosis.ttf

    - family: Maldives
      fonts:
        - asset: assets/fonts/others/Maldives.ttf

    - family: Nikoovers
      fonts:
        - asset: assets/fonts/others/Nikoovers-GORam.ttf
